language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t swclouddoctors/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true swclouddoctors/docker-react npm run test -- --coverage